### ISSUE TITLE
Refactor `PatriciaTrie`

### ISSUE THREAD

**Issue by awskii** [erigontech/erigon#11326]
`ProcessKeys/ProcessUpdates/ProcessTree` was added to maintain similar functionality with different approaches to passing updates list.

`UpdateTree` is not actually a tree and mostly we do use it as a map of `struct{}` and it also holds `Mode` which decides if we have all updates in memory or have to fetch them from domains during execution.

I want to change:
- [x] `UpdateTree -> Updates` #11439 
- [x] keep only one processing method in interface - let `Updates.Mode` decide how they will be gathered, for Trie it should be all the same (trie does reads from domains during unfold anyway even if `ModeUpdates` is used. #11517
- [x] make `Cell` unexported and for State related (Exported) fields use an (embedded) `Update` instead #11517
- [x] change `PatriciaContext` to work not with `Cells` but with `Updates` eg `GetAccount(addr) (*Update, error) to ease generalisation
- [ ] clarify downHashedKey
- [x] Skip sort of BranchData after commitment #11438 
- [x] hash and collect updated keys as they come https://github.com/erigontech/erigon/pull/11440
- [x] remove similar methods from `Trie` interface #11517
- [x] remove plain/hashed key from `Update` #11528
- [x] remove List method of `Updates` #11528

**Comment by awskii** [comment]
For now i decided to keep both `btree[Updates] and map[string]struct{}` inside `Updates` and not doing one map of `*Update` to preserve implemented ability to partially change Updates and have them ordered.
