### ISSUE TITLE
ErigonDB: prepare `agg` for new `entity-set` [meta-issue]

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#13261]
SharedDomains: less use of private method and then move SharedDomain to `inmemstate` package (because it based on kv.TemporalTx):
- [x] "less direct agg use": remove `DiscardHistory/EnableHistory` in favor of schema 
- [x] "less direct agg use": remove `sd.aggTx.d[kv.CommitmentDomain].Files()` add API `Files(domain)` https://github.com/erigontech/erigon/pull/14009
- [x] "less direct agg use": `SharedDomains.SetTx` must accept `kv.TemporalTx` 
- [ ] "less direct agg use": ...
- [ ] "less hardcoded domain names in agg" -> "readiness for multiple EntitySet. Or new agg with another EntitySet." (and maybe rediness for "dirtyFiles: to not require domain-alignment")

- [ ] "dirtyFiles: to not require domain-alignment" -> "easier add new entity to existing EntitySet. and re-gen 1 existing entity"
- [x] #13325
- [x] #13326
- [x] "extract replaceKeysInValues logic out of agg.go" -- address [this](https://github.com/erigontech/erigon/pull/13444/files#r1917638547) comment
- [x] #13328
- [ ] "visibleFilesMinimaxTxNum atomic - seems can be replaced by BeginFilesRo+calcMiniMax(entitesSet)"
- [ ] "AggregatorRoTx) findMergeRange has much biz-logic - about all domains"
- [x] "RestrictSubsetFileDeletions - actually is a hack - and not so safe hack. Not safe - because it's bool - and it called from many places and goroutines. Somehow need eliminate it. We have native way to protect some files from deletion - open read transaction on it (it will guarantee file existence until end of transaction) - we don't need 2nd mechanic"
- [ ] "reintroduce MaxReorgDepthV3 logic when collating files" - https://github.com/erigontech/erigon/issues/12763 - maybe PruneExecutionStage has this logic. MaxReorgDepthV3 - must be measured in TxNums, not in Steps.
- [x] new method HistoryStartFrom not added to grpc:  https://github.com/erigontech/erigon/issues/13173
- [x] #13432
- [ ] buildMissedAccessors duplicate code: https://github.com/erigontech/erigon/issues/12798
- [ ] recalcVisibleFiles: make it self-contained, move more checks inside: https://github.com/erigontech/erigon/issues/13174
- [ ]  https://github.com/erigontech/erigon/issues/13243
- [ ]  Avoid the use of `ForceReopenAggCtx` - it's a hack
- [x] #13434
- [x] tx param should be last in `GetAsOf` https://github.com/erigontech/erigon/pull/14007

Out of scope: SharedDomains, Commitment code in agg, ParallelExec. 

Future tasks: 
- [ ] we have inverted_index_stream.go and history_stream.go - they have much repeatative logic and not always follow same code-patterns. And not very clear naming. (low-priority and complexity-high).
- [ ] "BuildFilesInBackground" - is main func and BuildFiles based on it. But must be opposite. Because in Golang normal code is blocking - and it's easy to turn blocking code to non-blocking. (low prio)
- [ ] `findMergeRange` - duplicated code in domain/hist/ii. need re-visit logic. Sometime i see `erigon seg retire` does merge only domain files - but not history.  

- [ ] More type-safety: own type of TxNum, Step

**Comment by AskAlexSharov** [comment]
closing - mostly done. and there are other Epics exist
